config/routes.rb
Rails.application.routes.draw do
  root   'users#index'
  get    'signup',  to: 'users#new'
  get    'signin',  to: 'sessions#new'
  get    'rooms/show'
  get    'users',   to: 'users#index'
  delete 'signout', to: 'sessions#destroy'


  resources :users, only: [:show, :new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :communities
  resources :communities do
    post 'add' => 'joins#create'
    delete 'delete' => 'joins#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
	has_many :joins
  has_many :users, through: :joins

  validates :name,    presence: true # 名前空だめ
  validates :content, presence: true # 概要空だめ

  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Community.where(['name LIKE ?', "%#{search}%"])
    else
      Community.all #全て表示。
    end
  end
end

app/models/join.rb
class Join < ApplicationRecord
	belongs_to :user
    belongs_to :community
end

app/models/message.rb
class Message < ApplicationRecord
 after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :joins
    has_many :communities, through: :joins

    #名前
    validates :name,  presence: true, length: { maximum: 50 }

    #メール
    VALID_EMAIL_REGEX = /\As[0-9]{7}+@[u|s].tsukuba.ac.jp/
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    #パスワード
    validates :password, presence: true

    mount_uploader :picture, PictureUploader

    before_save { email.downcase! }
  
    has_secure_password
  
    def self.new_remember_token
      SecureRandom.urlsafe_base64
    end
  
    def self.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    #ViewのFormで取得したパラメータをモデルに渡す
    @communities = Community.search(params[:search])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :content)
    end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  def create
    user=current_user
    community=Community.find(params[:community_id])
    if Join.where(community_id: params[:community_id]).count >= 1
      flash[:notice] = "#{community.name}に参加できません"
      redirect_to communities_path
      # elsif User.where(sex: params[:sex]) == '女'
      # flash[:alert] = "あなたは女性なので参加できません"
      # redirect_to communities_path
    elsif Join.create(user_id: user.id,community_id:community.id)
      redirect_to community
    else
      redirect_to root_url
    end
  end

  def destroy
    user=current_user
    community=Community.find(params[:community_id])
    if join=Join.find_by(user_id: user.id,community_id:community.id)
      join.delete
      redirect_to current_user
    else
      redirect_to root_url
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
   @messages = Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        sign_in user
        redirect_to user
      else
        flash.now[:danger] = '無効な値です'
        render 'new'
      end
    end
  
    def destroy
      sign_out
      redirect_to root_url
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :signed_in_user, only: [:edit, :update]
    before_action :correct_user, only: [:edit, :update]
  
    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        sign_in @user
        redirect_to @user
      else
        render 'new'
      end
    end
  
    def update
      if @user.update_attributes(user_params)
        redirect_to @user
      else
        render 'edit'
      end
    end
  
    private
  
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture, :gakurui, :gakunen, :sex, :circle, :bite, :birthday, :hobby, :comment)
      end
  
      def correct_user
        @user = User.find(params[:id])
        redirect_to root_url unless current_user?(@user)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "Tsuxi"
    title = @page_title + " | " + title if @page_title

    return title
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
      remember_token = User.new_remember_token
      cookies.permanent[:remember_token] = remember_token
      user.update_attribute(:remember_token, User.encrypt(remember_token))
      self.current_user = user
    end
  
    def sign_out
      self.current_user = nil
      cookies.delete(:remember_token)
    end
  
    def current_user=(user)
      @current_user = user
    end
  
    def current_user
      remember_token = User.encrypt(cookies[:remember_token])
      @current_user ||= User.find_by(remember_token: remember_token)
    end
  
    def current_user?(user)
      user == current_user
    end
  
    def signed_in?
      !current_user.nil?
    end
  
    def signed_in_user
      redirect_to signin_url unless signed_in?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/_form.html.erb
<%= form_with(model: community, local: true) do |form| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :コミュニティ名 %>
    <%= form.text_field :name, id: :community_name %>
  </div>

  <div class="field">
    <%= form.label :概要 %>
    <%= form.text_field :content, id: :community_content %>
  </div>

  <div class="actions">
    <%= form.submit '作成'%>
  </div>
<% end %>

app/views/communities/edit.html.erb
<% @page_title = "コミュニティ編集" %>

<h1>Editing Community</h1>

<%= render 'form', community: @community %>

<%= link_to '詳細', @community %> |
<%= link_to '一覧に戻る', communities_path %>

app/views/communities/index.html.erb
<% @page_title = "コミュニティ一覧" %>

<p id="notice"><%= notice %></p>

<% if flash.now[:notice] %>
<% end %>

<h1>コミュニティ一覧</h1>

<%= form_tag communities_path, :method => 'get' do %> <%#　projects_pathはモデル名で読みかえること %>
  <p>コミュニティを検索</p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "検索", :name => nil %>
  <p></p>
<% end %>
 
 
<%= yield %>
 
<table border = "1">
  <tbody>
    <% @communities.each do |community| %>
      <tr>
        <td><center><%= community.name %><br>（概要：<%= community.content %>）</center></td>
          <% if !Join.exists?(user_id:current_user.id,community_id:community.id) %>
            <td><%= link_to "参加", community_add_path(community),method: :post %></td>
          <% else %>
            <td><%= link_to "退出",community_delete_path(community),method: :delete %></td>
          <% end %>
        <td><%= link_to '詳細', community %></td>
        <td><%= link_to '編集', edit_community_path(community) %></td>
        <td><%= link_to '削除', community, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規コミュニティを作成', new_community_path %>

app/views/communities/new.html.erb
<% @page_title = "コミュニティ作成" %>
<h1>新規コミュニティを作成</h1>

<%= render 'form', community: @community %>
<%= link_to '一覧に戻る', communities_path %>

app/views/communities/show.html.erb
<% @page_title = "詳細" %>

<p id="notice"><%= notice %></p>

<%# if flash[:notice] %>
<!--  <p><%#= flash[:notice] %></p>-->
<%# end %>

<p>
  <strong>コミュニティ名:</strong>
  <%= @community.name %>
</p>

<p>
  <strong>概要:</strong>
  <%= @community.content %>
</p>
<p>参加者一覧</p>
<p><% @community.users.each do |user| %>
       <%= image_tag(user.picture_url, :class => 'user_image2' ) if user.picture.present? %>
   <% end %>
</p>

<%= link_to '編集', edit_community_path(@community) %> |
<%= link_to 'マイページに戻る', current_user %> |
<%= link_to '一覧に戻る', communities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
  <% if signed_in? %>
  <li><%= link_to 'コミュニティ一覧', communities_path %></li>
  <li><%= link_to 'マイページ', current_user %></li>
  <li><%= link_to 'ログアウト', signout_path, method: :delete %></li>
  <% else %>
  <li><%= link_to 'ログイン', signin_path %></li>
  <li><%= link_to 'アカウント作成', signup_path %></li>
  <% end %>
</ul>


<!-------------------------------------------あとで完成させる------------------------------------------------->
<!--<nav class="navbar navbar-expand-md navbar-dark bg-blue mb-4" >-->
<!--  <a class="navbar-brand" href="#">Topnavbar</a>-->
<!--  <div>-->
<!--    <ul class="navbar-nav mr-auto">-->
<!--        <a class="nav-link" href="#">Home</a>-->
<!--        <a class="nav-link" href="#">Home</a>-->
<!--        <a class="nav-link" href="#">Home</a>-->
<!--    </ul>-->
<!--  </div>-->
<!--</nav>-->


<hr>

<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= message.content %></p>
</div>

app/views/rooms/show.html.erb
<% @page_title = "チャット" %>

<h1>Chat room</h1>
<p>Find me in app/views/rooms/show.html.erb</p>

<div id="messages">
  <%= render @messages %>
</div>

<form>
  <label>Say something:
   <input type="text" data-behavior="room_speaker">
  </label>
</form>

app/views/users/edit.html.erb
<% @page_title = "編集" %>
<h1>アカウント編集</h1>

<%= form_for(@user) do |f| %>

  <table border="1">
    <tr>
      <th><%= f.label :name, '名前' %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :email, 'メールアドレス' %></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th><%= f.label :password, 'パスワード' %></th>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <th><%= f.label :password_confirmation, '確認' %></th>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr>
        <th><%= f.label :picture, 'アイコン' %></th>
        <td><%= f.file_field :picture, id: :user_picture %></td>
    </tr>
    <tr>
      <th><%= f.label :gakurui, '学類' %></th>
      <td><%= f.select :gakurui,[["人文学類", "人文学類"], ["比較文化学類", "比較文化学類"],
       ["日本語・日本文化学類", "日本語・日本文化学類"], ["社会学類", "社会学類"],
      ["国際総合学類", "国際総合学類"], ["教育学類", "教育学類"],
      ["心理学類", "心理学類"], ["障害科学類", "障害科学類"],
      ["生物学類", "生物学類"], ["生物資源学類", "生物資源学類"],
      ["地球学類", "地球学類"], ["数学類", "数学類"], ["物理学類", "物理学類"],
      ["化学類", "化学類"], ["応用理工学類", "応用理工学類"], ["工学システム学類", "工学システム学類"],
      ["社会工学類", "社会工学類"], ["情報科学類", "情報科学類"], ["情報メディア創成", "情報メディア創成"],
      ["知識情報・図書館学類", "知識情報・図書館学類"], ["医学類", "医学類"], ["看護学類", "看護学類"],
      ["医療科学類", "医療科学類"], ["体育専門学群", "体育専門学群"], ["芸術専門学群", "芸術専門学群"]] %></td>
    </tr>
    <tr>
      <th><%= f.label :gakunen, '学年' %></th>
      <td><%= f.select :gakunen,[["1年", "1年"], ["2年", "2年"], ["3年", "3年"], ["4年", "4年"]] %></td>
    </tr>
    <tr>
      <th><%= f.label :sex, '性別' %></th>
      <td><%= f.select :sex,[["男", "男"], ["女", "女"]] %></td>
    </tr>
    <tr>
      <th><%= f.label :circle, 'サークル' %></th>
      <td><%= f.text_field :circle %></td>
    </tr>
    <tr>
      <th><%= f.label :bite, 'バイト' %></th>
      <td><%= f.text_field :bite %></td>
    </tr>
    <tr>
      <th><%= f.label :birthday, '生年月日' %></th>
      <td><%= f.date_field :birthday %></td>
    </tr>
    <tr>
      <th><%= f.label :hobby, '趣味' %></th>
      <td><%= f.text_field :hobby %></td>
    </tr>
    <tr>
      <th><%= f.label :comment, '一言' %></th>
      <td><%= f.text_area :comment %></td>
    </tr>

  </table>

  <%= f.submit 'アカウントを編集する' %>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <h1 class="cp_h1title">TSUXI</h1>
</div>

app/views/users/new.html.erb
<% @page_title = "アカウント作成" %>
<h1>アカウント作成</h1>



<%= form_for(@user) do |f| %>

  <table border="1">
    <tr>
      <th><%= f.label :name, '名前' %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :email, 'メールアドレス' %></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th><%= f.label :password, 'パスワード' %></th>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <th><%= f.label :password_confirmation, '確認' %></th>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr>
        <th><%= f.label :picture, 'アイコン' %></th>
        <td><%= f.file_field :picture, id: :user_picture %></td>
    </tr>
    <tr>
      <th><%= f.label :gakurui, '学類' %></th>
      <td><%= f.select :gakurui,[["人文学類", "人文学類"], ["比較文化学類", "比較文化学類"],
       ["日本語・日本文化学類", "日本語・日本文化学類"], ["社会学類", "社会学類"],
      ["国際総合学類", "国際総合学類"], ["教育学類", "教育学類"],
      ["心理学類", "心理学類"], ["障害科学類", "障害科学類"],
      ["生物学類", "生物学類"], ["生物資源学類", "生物資源学類"],
      ["地球学類", "地球学類"], ["数学類", "数学類"], ["物理学類", "物理学類"],
      ["化学類", "化学類"], ["応用理工学類", "応用理工学類"], ["工学システム学類", "工学システム学類"],
      ["社会工学類", "社会工学類"], ["情報科学類", "情報科学類"], ["情報メディア創成", "情報メディア創成"],
      ["知識情報・図書館学類", "知識情報・図書館学類"], ["医学類", "医学類"], ["看護学類", "看護学類"],
      ["医療科学類", "医療科学類"], ["体育専門学群", "体育専門学群"], ["芸術専門学群", "芸術専門学群"]] %></td>
    </tr>
    <tr>
      <th><%= f.label :gakunen, '学年' %></th>
      <td><%= f.select :gakunen,[["1年", "1年"], ["2年", "2年"], ["3年", "3年"], ["4年", "4年"]] %></td>
    </tr>
    <tr>
      <th><%= f.label :sex, '性別' %></th>
      <td><%= f.select :sex,[["男", "男"], ["女", "女"]] %></td>
    </tr>
    <tr>
      <th><%= f.label :circle, 'サークル' %></th>
      <td><%= f.text_field :circle %></td>
    </tr>
    <tr>
      <th><%= f.label :bite, 'バイト' %></th>
      <td><%= f.text_field :bite %></td>
    </tr>
    <tr>
      <th><%= f.label :birthday, '生年月日' %></th>
      <td><%= f.date_field :birthday %></td>
    </tr>
    <tr>
      <th><%= f.label :hobby, '趣味' %></th>
      <td><%= f.text_field :hobby %></td>
    </tr>
    <tr>
      <th><%= f.label :comment, '一言' %></th>
      <td><%= f.text_area :comment %></td>
    </tr>
  </table>

  <%= f.submit 'アカウントを作成する' %>

<% end %>

app/views/users/show.html.erb
<% @page_title = "マイページ" %>
<div class="container">
  <br><br>
  <h1>マイページ</h1>
  <br><br>

  <%= image_tag(@user.picture_url, :class => 'user_image' ) if @user.picture.present? %>
  <br><br><br>
  <h1><%= @user.name %></h1>
  <h3>学類：<%= @user.gakurui %></h3>
  <h3>学年：<%= @user.gakunen %></h3>
  <h3>性別：<%= @user.sex %></h3>
  <h3>サークル：<%= @user.circle %></h3>
  <h3>バイト：<%= @user.bite %></h3>
  <h3>生年月日：<%= @user.birthday %></h3>
  <h3>趣味：<%= @user.hobby %></h3>
  <h3>ひとこと：<%= @user.comment %></h3>

  <br><br><br><br><br>
  <% if current_user?(@user) %>
  <p><%= link_to '編集', edit_user_path %></p>
  <br>
  <h1>参加しているコミュニティ一覧</h1>
  <table border = "1">
    <tbody>
          <% @user.communities.uniq.each do |community| %>
          　<tr>
              <td><%= community.name %></td>
              <td><%= link_to 'チャットルームへ', :controller => "rooms", :action=>"show" %></td>
              <td><%= link_to "退出",community_delete_path(community),method: :delete %></td>
              <td><%= link_to '詳細', community %></td>
            </tr>
          <% end %>
    </tbody>
  </table>

  <% end %>
</div>